"""Add id as primary key to Rating_votes

Revision ID: 0ca31169a91d
Revises: 
Create Date: 2023-04-24 12:41:53.050448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca31169a91d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id_vote', sa.Integer(), nullable=True))
        batch_op.drop_constraint('comment_votes_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comment_votes_comment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'comments', ['comment_id_vote'], ['comment_id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comments_rating_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'rating', ['rating_id'], ['rating_id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('rating_rater_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['rater_id'], ['user_id'])

    with op.batch_alter_table('rating_votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating_id_vote', sa.Integer(), nullable=True))
        batch_op.drop_constraint('rating_votes_rating_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('rating_votes_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])
        batch_op.create_foreign_key(None, 'rating', ['rating_id_vote'], ['rating_id'])
        batch_op.drop_column('rating_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rating_votes_user_id_fkey', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('rating_votes_rating_id_fkey', 'rating', ['rating_id'], ['rating_id'], ondelete='CASCADE')
        batch_op.drop_column('rating_id_vote')
        batch_op.drop_column('id')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rating_rater_id_fkey', 'users', ['rater_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_rating_id_fkey', 'rating', ['rating_id'], ['rating_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('comments_user_id_fkey', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('comment_votes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_votes_comment_id_fkey', 'comments', ['comment_id'], ['comment_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('comment_votes_user_id_fkey', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_column('comment_id_vote')

    # ### end Alembic commands ###
