"""Add id as primary key to Rating_votes

Revision ID: ab7222851394
Revises: 0ca31169a91d
Create Date: 2023-04-24 12:43:09.431952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7222851394'
down_revision = '0ca31169a91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_votes', schema=None) as batch_op:
        batch_op.drop_column('rating_id')

    # ### end Alembic commands ###
